"""chat_models_refactoring

Revision ID: e3f55acf8965
Revises: d0cb6a1d1e52
Create Date: 2026-07-18 17:14:20.817821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3f55acf8965'
down_revision: Union[str, Sequence[str], None] = 'd0cb6a1d1e52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_conversations', sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('chat_messages', sa.Column('token_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'token_count')
    op.drop_column('chat_conversations', 'last_message_at')
    # ### end Alembic commands ###
